cd ../
cd traces/traceplayer
touch log_file0.txt
touch log_file1.txt
touch log_file2.txt
touch log_file3.txt
touch log_file4.txt
touch log_file5.txt
touch log_file6.txt
touch log_file7.txt
touch log_file8.txt
cd ../../
cd verilator
